version: "3"
services:
  jupyteo-hub:
    env_file:
      - .env
      - secrets/oauth.env
    build:
      context: ../
      dockerfile: "./hub/Dockerfile"
    image: "reg.jupyteo.com/jupyterhub:0.9.4-2.0.0"
    container_name: jupyteo-hub
    # mount the docker socket
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./jupyterhub_config.py:/tmp/jupyterhub_config.py
      - ./run-from-compose.sh:/run-from-compose.sh
      - /opt/data/priv/:/opt/data/priv/
      - /opt/var/:/opt/var/
    networks:
      - jupyteo-net
    ports:
      - "8000:8000"
    hostname: jupyteo-hub
    environment:
      DOCKER_NETWORK_NAME: ${DOCKER_NETWORK_NAME}
      DOCKER_SPAWN_NOTEBOOK_IMAGE: ${DOCKER_SPAWN_NOTEBOOK_IMAGE}
      DOCKER_NOTEBOOK_DIR: ${DOCKER_NOTEBOOK_DIR}
      SPAWN_USER: ${SPAWN_USER}
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    command: sh /run-from-compose.sh

networks:
  jupyteo-net:
    external:
      name: jupyteo-net